In [882]:
import pandas as pd
import numpy as np

In [883]:
dt_frame = pd.read_csv("Part_PropertiesLinks3.csv", sep=";")

In [884]:
lınks = dt_frame["LINK"]

In [885]:
dt_frame

PARTNO                                               LINK  \
0          141A3505-158  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
1            141A3913-3  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
2           141A8112-26  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
3          141A8131-110  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
4            141A8151-5  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
...                 ...                                                ...   
1304  UM123T040884000-T  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
1305   UM123T040886000T  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
1306    UM128T021031600  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
1307    UM460T010025000  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   
1308    V5762575320102T  \\ORTAKALAN\ERP_UYGULAMA_DOSYALARI\EFAB_PLNGDO...   

                       DIMENSIONCODE        FINALCONDITION     GAGE  WIDTH  \
0     EXTRUSION METALLIC              T62                       NaN    NaN   
1     EXTRUSION METALLIC              T73                       NaN    NaN   
2     SHEET METALLIC                  T62                     0.090    6.0   
3     SHEET METALLIC                  T62                     0.063    7.3   
4     EXTRUSION METALLIC              T42                       NaN    NaN   
...                              ...                   ...      ...    ...   
1304  ROUND BAR METALLIC              H1025                     NaN    NaN   
1305  ROUND BAR METALLIC              H1025                     NaN    NaN   
1306  ROUND BAR METALLIC              T7351                     NaN    NaN   
1307  ROUND BAR METALLIC              H1025                     NaN    NaN   
1308  PLATE METALLIC                  T7451                 180.000  210.0   

      LENGTH                               EXTRUSIONNO GRAIN_DIRECTION  \
0       45.0  BAC1514-3320                                           N   
1       40.0  BAC1505-100361                                         N   
2       94.0                                       NaN               N   
3       17.0                                       NaN               N   
4      144.0  BAC1517-2767                                           N   
...      ...                                       ...             ...   
1304    35.0                                                         N   
1305    30.0                                                         N   
1306   190.0                                                         N   
1307   115.0                                       NaN               N   
1308   615.0                                       NaN               Y   

                                           MATERIALSPEC MATERIALTYPE  \
0     QQ-A-200/11                                   ...           al   
1     QQ-A-200/11                                   ...           al   
2     QQ-A-250/13                                   ...           al   
3     QQ-A-250/13                                   ...           al   
4     QQ-A-200/3                                    ...           al   
...                                                 ...          ...   
1304  AMS 5659                                      ...           ti   
1305  AMS 5659                                      ...           ti   
1306  QQ-A-225/9                                    ...        steel   
1307  AMS 5659                                      ...           al   
1308  ABS 5324                                      ...           al   

      MULTIPLE     MEDIAN  
0            1   2.900000  
1            1   1.614286  
2            1   1.680000  
3            1   0.395238  
4            1  31.566667  
...        ...        ...  
1304         1   1.350000  
1305         1   0.584211  
1306         1   4.600000  
1307         1   0.675000  
1308         2   0.536364  

[1309 rows x 13 columns]

In [886]:
data = dt_frame.groupby(['PARTNO'], as_index=False,dropna=False).all("PARTNO")

In [887]:
data = dt_frame[["GAGE", "WIDTH", "LENGTH","GRAIN_DIRECTION","MATERIALTYPE","MULTIPLE"]]
y_median  =  dt_frame["MEDIAN"]

In [888]:
data

GAGE  WIDTH  LENGTH GRAIN_DIRECTION MATERIALTYPE  MULTIPLE
0         NaN    NaN    45.0               N           al         1
1         NaN    NaN    40.0               N           al         1
2       0.090    6.0    94.0               N           al         1
3       0.063    7.3    17.0               N           al         1
4         NaN    NaN   144.0               N           al         1
...       ...    ...     ...             ...          ...       ...
1304      NaN    NaN    35.0               N           ti         1
1305      NaN    NaN    30.0               N           ti         1
1306      NaN    NaN   190.0               N        steel         1
1307      NaN    NaN   115.0               N           al         1
1308  180.000  210.0   615.0               Y           al         2

[1309 rows x 6 columns]

In [889]:
data.isnull().sum()

GAGE               394
WIDTH              381
LENGTH               0
GRAIN_DIRECTION      0
MATERIALTYPE         0
MULTIPLE             0
dtype: int64

In [890]:
data["WIDTH"].median()

73.5

In [891]:
data["GAGE"].median()

3.175

In [892]:
data["WIDTH"] = data.WIDTH.fillna(data.WIDTH.median())
data["GAGE"] = data.GAGE.fillna(0.001)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [893]:
data

GAGE  WIDTH  LENGTH GRAIN_DIRECTION MATERIALTYPE  MULTIPLE
0       0.001   73.5    45.0               N           al         1
1       0.001   73.5    40.0               N           al         1
2       0.090    6.0    94.0               N           al         1
3       0.063    7.3    17.0               N           al         1
4       0.001   73.5   144.0               N           al         1
...       ...    ...     ...             ...          ...       ...
1304    0.001   73.5    35.0               N           ti         1
1305    0.001   73.5    30.0               N           ti         1
1306    0.001   73.5   190.0               N        steel         1
1307    0.001   73.5   115.0               N           al         1
1308  180.000  210.0   615.0               Y           al         2

[1309 rows x 6 columns]

In [894]:
from sklearn.preprocessing import LabelEncoder
from numpy import array

In [895]:
graın = array(data["GRAIN_DIRECTION"])
Lr = LabelEncoder()
integred_data = Lr.fit_transform(graın)
integred_data

array([0, 0, 0, ..., 0, 0, 1])

In [896]:
data["GRAIN_DIRECTION"] = integred_data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [897]:
data

GAGE  WIDTH  LENGTH  GRAIN_DIRECTION MATERIALTYPE  MULTIPLE
0       0.001   73.5    45.0                0           al         1
1       0.001   73.5    40.0                0           al         1
2       0.090    6.0    94.0                0           al         1
3       0.063    7.3    17.0                0           al         1
4       0.001   73.5   144.0                0           al         1
...       ...    ...     ...              ...          ...       ...
1304    0.001   73.5    35.0                0           ti         1
1305    0.001   73.5    30.0                0           ti         1
1306    0.001   73.5   190.0                0        steel         1
1307    0.001   73.5   115.0                0           al         1
1308  180.000  210.0   615.0                1           al         2

[1309 rows x 6 columns]

In [898]:
from sklearn.preprocessing import OneHotEncoder

In [899]:
material_lr = array(data["MATERIALTYPE"])
label_encoder_mat = LabelEncoder()
integer_encoded_mat = label_encoder_mat.fit_transform(material_lr)

In [900]:
material = array(data["MATERIALTYPE"])
onehot_encoder_mat = OneHotEncoder(sparse=False)
integer_encoded_mat_hot = integer_encoded_mat.reshape(len(integer_encoded_mat), 1)
onehot_encoded_mat = onehot_encoder_mat.fit_transform(integer_encoded_mat_hot)

In [901]:
data["MATERIALTYPE"] = onehot_encoded_mat

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [902]:
data

GAGE  WIDTH  LENGTH  GRAIN_DIRECTION  MATERIALTYPE  MULTIPLE
0       0.001   73.5    45.0                0           1.0         1
1       0.001   73.5    40.0                0           1.0         1
2       0.090    6.0    94.0                0           1.0         1
3       0.063    7.3    17.0                0           1.0         1
4       0.001   73.5   144.0                0           1.0         1
...       ...    ...     ...              ...           ...       ...
1304    0.001   73.5    35.0                0           0.0         1
1305    0.001   73.5    30.0                0           0.0         1
1306    0.001   73.5   190.0                0           0.0         1
1307    0.001   73.5   115.0                0           1.0         1
1308  180.000  210.0   615.0                1           1.0         2

[1309 rows x 6 columns]

In [903]:
multiple_lr = array(data["MULTIPLE"])
label_encoder_mult = LabelEncoder()
integer_encoded_mult = label_encoder_mult.fit_transform(multiple_lr)

In [904]:
multiple = array(data["MULTIPLE"])
onehot_encoder_mult = OneHotEncoder(sparse=False)
integer_encoded_mult_hot = integer_encoded_mult.reshape(len(integer_encoded_mult), 1)
onehot_encoded_mult = onehot_encoder_mult.fit_transform(integer_encoded_mult_hot)

In [905]:
data["MULTIPLE"] = onehot_encoded_mult

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [906]:
df = pd.read_excel("parcaSaat (1).xlsx", sheet_name="Sheet1")

In [907]:
df = df[["PARCANO", "TSAAT", "PARTNO"]]

In [908]:
dfff=df.groupby(['PARCANO'], as_index=False,dropna=False).agg("median")

In [909]:
dfff = dfff.reset_index(drop=True)

In [910]:
value=dfff['PARCANO'].isin(df['PARTNO'])

In [911]:
dfff['TrueFalse'] = value

In [912]:
(dfff['TrueFalse']).value_counts()[True]

1309

In [913]:
(dfff['TrueFalse']).value_counts()[False]

2095

In [914]:
dfff.drop(dfff[dfff.TrueFalse == False].index, inplace=True)

In [915]:
data_label = dfff[["PARCANO", "TSAAT"]]

In [916]:
data_label

PARCANO      TSAAT
0     10S25288724-238  18.750000
1        113A3111-901   6.850000
2        113A3111-902   7.100000
3         114A1612-3A   0.230556
4        116A9203-602   1.650000
...               ...        ...
3343  V5762514720001T   0.560400
3361  V5762575320102T   0.536364
3367   V5762709720000   0.592727
3374   V5762759620000   0.875000
3375   V5762759720000   0.592727

[1309 rows x 2 columns]

In [917]:
dt_frame.index == data_label.index

array([ True,  True,  True, ..., False, False, False])

In [918]:
data

GAGE  WIDTH  LENGTH  GRAIN_DIRECTION  MATERIALTYPE  MULTIPLE
0       0.001   73.5    45.0                0           1.0       1.0
1       0.001   73.5    40.0                0           1.0       1.0
2       0.090    6.0    94.0                0           1.0       1.0
3       0.063    7.3    17.0                0           1.0       1.0
4       0.001   73.5   144.0                0           1.0       1.0
...       ...    ...     ...              ...           ...       ...
1304    0.001   73.5    35.0                0           0.0       1.0
1305    0.001   73.5    30.0                0           0.0       1.0
1306    0.001   73.5   190.0                0           0.0       1.0
1307    0.001   73.5   115.0                0           1.0       1.0
1308  180.000  210.0   615.0                1           1.0       0.0

[1309 rows x 6 columns]

In [919]:
ga_lr = array(data["GAGE"])
label_encoder_ga = LabelEncoder()
integer_encoded_ga = label_encoder_ga.fit_transform(ga_lr)

onehot_encoder_ga = OneHotEncoder(sparse=False)
integer_encoded_ga_hot = integer_encoded_ga.reshape(len(integer_encoded_ga), 1)
onehot_encoded_ga = onehot_encoder_ga.fit_transform(integer_encoded_ga_hot)

In [920]:
wid_lr = array(data["WIDTH"])
label_encoder_wid = LabelEncoder()
integer_encoded_wid = label_encoder_wid.fit_transform(wid_lr)

onehot_encoder_wid = OneHotEncoder(sparse=False)
integer_encoded_wid_hot = integer_encoded_wid.reshape(len(integer_encoded_wid), 1)
onehot_encoded_wid = onehot_encoder_wid.fit_transform(integer_encoded_wid_hot)

In [921]:
he_lr = array(data["LENGTH"])
label_encoder_he = LabelEncoder()
integer_encoded_he = label_encoder_he.fit_transform(he_lr)

onehot_encoder_he = OneHotEncoder(sparse=False)
integer_encoded_he_hot = integer_encoded_he.reshape(len(integer_encoded_he), 1)
onehot_encoded_he = onehot_encoder_he.fit_transform(integer_encoded_he_hot)

In [922]:
# data["GAGE"] = onehot_encoded_ga
# data["WIDTH"] = onehot_encoded_wid
# data["LENGTH"] = onehot_encoded_he

In [923]:
data

GAGE  WIDTH  LENGTH  GRAIN_DIRECTION  MATERIALTYPE  MULTIPLE
0       0.001   73.5    45.0                0           1.0       1.0
1       0.001   73.5    40.0                0           1.0       1.0
2       0.090    6.0    94.0                0           1.0       1.0
3       0.063    7.3    17.0                0           1.0       1.0
4       0.001   73.5   144.0                0           1.0       1.0
...       ...    ...     ...              ...           ...       ...
1304    0.001   73.5    35.0                0           0.0       1.0
1305    0.001   73.5    30.0                0           0.0       1.0
1306    0.001   73.5   190.0                0           0.0       1.0
1307    0.001   73.5   115.0                0           1.0       1.0
1308  180.000  210.0   615.0                1           1.0       0.0

[1309 rows x 6 columns]

In [963]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import tree

from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import explained_variance_score


In [1005]:
x=data.values
y=y_median

In [1000]:
y = array(y)
y_encoder = LabelEncoder()
y_integer_encoded = y_encoder.fit_transform(y)

In [1001]:
onehot_encoder_y = OneHotEncoder(sparse=False)
integer_encoded_y_hot = y_integer_encoded.reshape(len(y_integer_encoded), 1)
onehot_encoded_y = onehot_encoder_y.fit_transform(integer_encoded_y_hot)

In [1002]:
y = onehot_encoded_y

In [1003]:
from sklearn.datasets import make_multilabel_classification

In [1004]:
# mlp for multi-label classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score

def get_dataset():
	X, y = make_multilabel_classification(n_samples=1000, n_features=6, n_classes=3, n_labels=5, random_state=41)
	return X, y
 
# get the model
def get_model(n_inputs, n_outputs):
	model = Sequential()
	model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
	model.add(Dense(n_outputs, activation='sigmoid'))
	model.compile(loss='binary_crossentropy', optimizer='adam')
	return model
 
# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
	results = list()
	n_inputs, n_outputs = X.shape[1], y.shape[1]
	# define evaluation procedure
	cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
	# enumerate folds
	for train_ix, test_ix in cv.split(X):
		# prepare data
		X_train, X_test = X[train_ix], X[test_ix]
		y_train, y_test = y[train_ix], y[test_ix]
		# define model
		model = get_model(n_inputs, n_outputs)
		# fit model
		model.fit(X_train, y_train, verbose=0, epochs=10)
		# make a prediction on the test set
		yhat = model.predict(X_test)
		# round probabilities to class labels
		yhat = yhat.round()
		# calculate accuracy
		acc = accuracy_score(y_test, yhat)
		# store result
		print('>%.3f' % acc)
		results.append(acc)
	return results
 
# load dataset
X, y = get_dataset()
# evaluate model
results = evaluate_model(X, y)
# summarize performance
print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))

>0.650
>0.610
>0.650
>0.710
>0.540
>0.640
>0.670
>0.560
>0.500
>0.730
>0.580
>0.590
>0.440
>0.680
>0.720
>0.680
>0.610
>0.620
>0.610
>0.620
>0.580
>0.650
>0.490
>0.620
>0.580
>0.510
>0.520
>0.560
>0.610
>0.660
Accuracy: 0.606 (0.069)


In [986]:
x, y = make_multilabel_classification(n_samples=1309, n_features=6, n_classes=3, n_labels=5, random_state=1)

In [987]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y_integer_encoded,test_size=.33,random_state=42)

In [988]:
print(x.shape, y.shape)

(1309, 6) (1309, 3)


In [989]:
x.shape

(1309, 6)

In [990]:
for i in range(10):
	print(x[i],y[i])

[ 3.  5. 14. 13.  7. 11.] [1 1 1]
[ 2.  9.  7. 27. 13.  2.] [0 1 0]
[ 5.  8. 10. 11. 12.  9.] [1 1 1]
[13.  7.  8.  6. 19.  9.] [1 1 1]
[ 3.  9.  9.  6. 16.  6.] [1 1 1]
[ 4.  5. 14. 18. 11.  6.] [1 1 0]
[13.  8. 14.  7.  5. 11.] [0 0 0]
[ 6.  4. 10. 15. 10.  4.] [1 1 0]
[ 5.  3. 13.  8.  8.  9.] [1 1 1]
[ 9.  3. 12.  5. 15.  3.] [1 0 0]


In [991]:
from keras.models import Sequential
from keras.layers import Dense

In [992]:
model = Sequential()
model.add(Dense(20, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam')

In [993]:
y_pred_forest = model.predict(X_test)

In [994]:
y_pred_forest.shape

(432, 1)

In [995]:
Y_test.shape

(432,)

In [996]:
explained_variance_score(Y_test,y_pred_forest)

7.062166103022349e-06